import os
from PyQt4 import QtGui,QtCore

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_password_manager(object):
    def setupUi(self, password_manager):
        password_manager.setObjectName(_fromUtf8("password_manager"))
        password_manager.resize(484, 400)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("Icons/manager.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        password_manager.setWindowIcon(icon)
        self.verticalLayout_5 = QtGui.QVBoxLayout(password_manager)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtGui.QLabel(password_manager)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtGui.QLabel(password_manager)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout.addWidget(self.label_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        spacerItem = QtGui.QSpacerItem(18, 6, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem)
        self.password_manager_table = QtGui.QTableWidget(password_manager)
        self.password_manager_table.setObjectName(_fromUtf8("password_manager_table"))
        self.password_manager_table.setColumnCount(2)
        self.password_manager_table.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.password_manager_table.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.password_manager_table.setHorizontalHeaderItem(1, item)
        self.verticalLayout_2.addWidget(self.password_manager_table)
        spacerItem1 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem1)
        self.verticalLayout_5.addLayout(self.verticalLayout_2)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.password_save_changes = QtGui.QPushButton(password_manager)
        self.password_save_changes.setObjectName(_fromUtf8("password_save_changes"))
        self.verticalLayout_4.addWidget(self.password_save_changes)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        spacerItem2 = QtGui.QSpacerItem(268, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_3.addItem(spacerItem2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.use_credential = QtGui.QPushButton(password_manager)
        self.use_credential.setObjectName(_fromUtf8("use_credential"))
        self.horizontalLayout.addWidget(self.use_credential)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.inser_credential = QtGui.QPushButton(password_manager)
        self.inser_credential.setObjectName(_fromUtf8("inser_credential"))
        self.horizontalLayout.addWidget(self.inser_credential)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.delete_credential = QtGui.QPushButton(password_manager)
        self.delete_credential.setObjectName(_fromUtf8("delete_credential"))
        self.horizontalLayout.addWidget(self.delete_credential)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)

        self.retranslateUi(password_manager)
        QtCore.QMetaObject.connectSlotsByName(password_manager)

    def retranslateUi(self, password_manager):
        password_manager.setWindowTitle(QtGui.QApplication.translate("password_manager", "Password Manager", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("password_manager", "Select or add database credentials to be used for the login process of the  database", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("password_manager", "login phase. Passwords are displayed as plain text.", None, QtGui.QApplication.UnicodeUTF8))
        self.password_manager_table.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("password_manager", "Username", None, QtGui.QApplication.UnicodeUTF8))
        self.password_manager_table.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("password_manager", "Password", None, QtGui.QApplication.UnicodeUTF8))
        self.password_save_changes.setText(QtGui.QApplication.translate("password_manager", "Save Changes", None, QtGui.QApplication.UnicodeUTF8))
        self.use_credential.setText(QtGui.QApplication.translate("password_manager", "  Use Selected Credential  ", None, QtGui.QApplication.UnicodeUTF8))
        self.inser_credential.setText(QtGui.QApplication.translate("password_manager", "   Insert New Login Credential  ", None, QtGui.QApplication.UnicodeUTF8))
        self.delete_credential.setText(QtGui.QApplication.translate("password_manager", "  Delete Credential  ", None, QtGui.QApplication.UnicodeUTF8))